USE [master]
GO

/****** Object:  Database [HiTechManagementDB]    Script Date: 4/17/2022 3:38:12 AM ******/
CREATE DATABASE [HiTechManagementDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HiTechManagementDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HiTechManagementDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HiTechManagementDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HiTechManagementDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HiTechManagementDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HiTechManagementDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HiTechManagementDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HiTechManagementDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HiTechManagementDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HiTechManagementDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HiTechManagementDB] SET  MULTI_USER 
GO

ALTER DATABASE [HiTechManagementDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HiTechManagementDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HiTechManagementDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HiTechManagementDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HiTechManagementDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HiTechManagementDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HiTechManagementDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HiTechManagementDB] SET  READ_WRITE 
GO

