//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ISBN { get; set; }
        public string Title { get; set; }
        public decimal UnitPrice { get; set; }
        public int Year { get; set; }
        public int QOH { get; set; }
        public int CategoryId { get; set; }
        public int PublisherId { get; set; }
    }
}
